// <auto-generated />
namespace EntityFrameworkCodeFirstApp_JustConsoleApp_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createCategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createCategories));
        
        string IMigrationMetadata.Id
        {
            get { return "202104071942557_createCategories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
